### ISSUE TITLE
examples of language line options

### ISSUE THREAD

**Issue by pcause** [benjamonnguyen/obsidian-inline-todotxt#15]
can you provide examples for use of the "language line" options, as you have with other features.  for example where does get get the items.  is it a list of notes?  same for link?  link to a note?  inside or outside the vault.  what is the difference.

**Comment by benjamonnguyen** [comment]
@pcause those language line option have not been implemented yet

**Comment by pcause** [comment]
thanks.  not clear from the README.  Might indicate it.

OK, I see the box isn't checked.  Sorry, but quick look I missed that.
