### ISSUE TITLE
Would like to have aggregated priorities (A~D) displayed at the top

### ISSUE THREAD

**Issue by FinnsonRyan** [benjamonnguyen/obsidian-inline-todotxt#16]
希望能将优先事项（A~D）聚合显示在顶部
类似于目前项目的呈现方式，只不过是自动的跨过项目隔断，将优先事项置顶聚合显示
--------
Would like to see priorities (A~D) aggregated at the top Similar to the way projects are currently presented, except that they are automatically aggregated at the top across project partitions.

**Comment by FinnsonRyan** [comment]
It's a really great program!

**Comment by benjamonnguyen** [comment]
@FinnsonRyan Thank you!

Can you provide a few examples of what you mean?
