### ISSUE TITLE
Group by context

### ISSUE THREAD

**Issue by anevaiopvn** [benjamonnguyen/obsidian-inline-todotxt#17]
Hi. If possible, I would like to have an option to group by context, instead of the default behavior of grouping by project.

**Comment by benjamonnguyen** [comment]
@anevaiopvn once filter option is available, you will be able to filter by context, but I am not planning on implementing an option to disable project grouping

**Comment by anevaiopvn** [comment]
@benjamonnguyen Ok, thanks for quick response.
