### ISSUE TITLE
Codeblock is not loading

### ISSUE THREAD

**Issue by Jefferderp** [benjamonnguyen/obsidian-inline-todotxt#21]
Hello,

I was eager to help test the new v0.2.0, but for some strange reason, the plugin is not loading. Obsidian is rendering a generic codeblock rather than the plugin's interface. I'm experiencing the same issue with v0.1.0. Curiously, I did not have this issue a week ago. The only notable changes to my vault are that I've updated Obsidian to the latest version. I've uninstalled the plugin, installed via Obsidian and BRAT, and restarted my vault. Any ideas?

My codeblock is formatted as such:

![image](https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/assets/13530594/ab0ee26c-3489-429a-8c74-2f61771b8d55)

Are there any debug logs I can reference?

Thanks!

**Comment by Jefferderp** [comment]
...and now it works. I didn't try anything new.

Whatever!

**Comment by Jefferderp** [comment]
This issue appeared again when I noticed the features from 0.2.0 were missing, despite the manifest stating I was on that version. I restarted Obsidian, and the plugin was inactive again.

It doesn't appear to be related to any other installed/active plugins. I'm not in source mode, and there are no other obvious causes. I'm very familiar with Obsidian, so I don't think I'm overlooking anything obvious.

I can't for the life of me figure out what the cause is.

**Comment by benjamonnguyen** [comment]
Can you use ctrl+shift+i to access the Developer console and see if there are any error messages?

**Comment by benjamonnguyen** [comment]
On re-reading your comment, I think the solution is uninstall Todotxt and reinstall via BRAT (not Obsidian).

**Comment by Jefferderp** [comment]
Unfortunately I've already tried that.

Here's the only error I'm seeing in the console:

```javascript
Uncaught (in promise) Error: Attempting to register an existing file extension "txt"
    at t.registerExtensions (app.js:1:1771428)
    at t.registerExtensions (app.js:1:2020712)
    at TodotxtCodeblocksPlugin.onload (plugin:todotxt-codeblocks:2432:10)
```

**Comment by benjamonnguyen** [comment]
Ah ok I'll fix that. I'm assuming you have another todotxt plugin? You can try disabling it for now while I work on the fix.

**Comment by Jefferderp** [comment]
I'm glad you mentioned that, it sparked an idea!

I have the [openasmd](https://github.com/kursad-k/obsidian-openasmd) plugin which allows plain-text editing of txt files. It didn't occur to me that it would be in conflict with `todotxt-codeblocks`, but of course it makes sense.

If the two are incompatible, that's no problem, I can work around it.

Problem solved. Thanks!
