### ISSUE TITLE
cannot install problem

### ISSUE THREAD

**Issue by arata-uesugi** [benjamonnguyen/obsidian-inline-todotxt#26]
This plugin could not be installed on Obsidian.

**Comment by Amina-Delali** [comment]
I have the same issue 
<img width="878" alt="image" src="https://github.com/user-attachments/assets/8f3c0241-75fa-4b94-abb6-9bc6e0ee14e7">

**Comment by benjamonnguyen** [comment]
Could you provide any error logs from the [dev console](https://forum.obsidian.md/t/opening-developer-console/66755) and details like your OS?

**Comment by Amina-Delali** [comment]
> Could you provide any error logs from the [dev console](https://forum.obsidian.md/t/opening-developer-console/66755) and details like your OS?

The OS: **Microsoft Windows 11 Pro**, version: **10.0.22631** 
Obsidian Version: **v1.6.7**
And here the **dev console** log: 

<img width="936" alt="image" src="https://github.com/user-attachments/assets/cfdfe016-5658-473e-adb0-93dc5b3f3d08">

ps: Thanks for the quick answer!

**Comment by Amina-Delali** [comment]
> Could you provide any error logs from the [dev console](https://forum.obsidian.md/t/opening-developer-console/66755) and details like your OS?

I had a backup of my previous Obsidian vault, where the plugin was installed. So, I copied the files , and it worked with the new vault . But the update  doesn't work. The working version is: **0.2.1** 

<img width="585" alt="image" src="https://github.com/user-attachments/assets/65a5e2ce-92c2-41e8-b348-4d7c0209f618">


> Could you provide any error logs from the [dev console](https://forum.obsidian.md/t/opening-developer-console/66755) and details like your OS?

**Comment by Cabalua** [comment]
Same problem here.  Linux Mint / Obsidian 1.6.7 / TodoTxt Codeblocks 0.3.0

**Comment by benjamonnguyen** [comment]
So sorry for the delay y'all. Issue has been resolved with release 0.3.0.
