### ISSUE TITLE
error with folder that has spaces??

### ISSUE THREAD

**Issue by ksdavidc** [benjamonnguyen/obsidian-inline-todotxt#27]
If I  try to use a file in a subfolder that has spaces in teh name,  I get "does not follow syntax" message.

If I use a folder that does not have spaces I get no error. 

IF I use "%20" like in this codeblock,

````

```todotxt "[[todo.txt]] (2024-08-22)" src:Miscellaneous%20non%20KL/todo.txt
(A) 2024-08-25 another +goals
2024-08-22 test entry
(A) 2024-08-22 2024 -08-22 another test +project @write
```
````

to connect it with file "Miscellaneous%20non%20KL/todo.txt", I get an error 
<img width="289" alt="Screenshot 2024-08-22 at 9 32 25 PM" src="https://github.com/user-attachments/assets/a78e8ee3-a146-4396-a2ef-96e2e1bc2b12">

What am I doing wrong?

**Comment by Mauricioc93** [comment]
Hi benjamonnguyen,

I have the same issue. I am working on Windows, and I store my Obsidian vault on OneDrive, which has spaces in the folder names that I can't remove easily.

I tried using relative paths when doing tests in a codeblock (considering the vault folder as the root), and it created the .txt file in the desired subfolder. Sadly, it is unable to synchronize with the file any longer and I get the same error as the post above:
![codeblock](https://github.com/user-attachments/assets/63271f23-e9a2-421e-8cbe-826fa3cd0a6a)

I appreciate any help, thanks!!

**Comment by benjamonnguyen** [comment]
Thanks for bringing this to my attention! I'll handle this case in the next release.

**Comment by benjamonnguyen** [comment]
https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/releases/tag/0.3.1
