### ISSUE TITLE
priority in done task

### ISSUE THREAD

**Issue by udjer** [benjamonnguyen/obsidian-inline-todotxt#29]
Hi benjamonnguyen,

thanks for the great plugin (again), I really appreciate the thoughtful layout and the simplicity of the implementation!
And thanks also for fixing the update/install issue so swiftly!

I am wondering about how priority appears in a done task: when I create a task with priority, say

`(C) 2024-09-01 test task`

and then mark it complete using the plugin, I get

`x (C) 2024-09-01 2024-09-01 test task`

The retained priority at second position seems to make the item as open/not completed in other apps: e.g., `SwiftDo` doesn't show the task as complete, `todd` shows it as complete but fails at removing the completed mark.

Perhaps better to drop the priority on completion?

**Comment by benjamonnguyen** [comment]
Could you do a test for me and create a line in your todotxt file `x 2024-09-01 (C) 2024-09-01 test task` and see if it renders correctly and is able to be uncompleted in those 2 apps?

**Comment by udjer** [comment]
Thanks for getting back to me so swiftly!

I did a few experiments with apps that are available to me:
- obsidian: your plugin
- iOS: SwiftDo & 2do.txt
- MacOS/linux (python): todd & todo-txt-tui

The behaviour of how completed tasks deal with priority seems fairly inconsistent, at least, I wasn't able to detect any commonly compatible format/arrangement of priority/completion/creation dates.  Here is the test file:

```
(B) 2024-08-31 test prio-created
2024-08-31 (B) test created-prio
x (B) 2024-09-02 2024-08-31 test prio-done-created
x 2024-09-02 (B) 2024-08-31 test done-prio-created
x 2024-09-02 2024-08-31 (B) test done-created-prio
```

With each app, I tested how the file was displayed and then how undoing tasks (if possible) in the respective app reflected (for SwiftDo, I also checked how your plugin shows the undone tasks) - see screenshots below, the image titles (visible on hover) read `<app-name><number of undone tasks>`.

Hope that helps a bit...

- Obsidian codeblock plugin (on iOS): for reflection of how tasks undone in SwiftDo (below) mirror in the plugin
<div>
<img src="https://github.com/user-attachments/assets/2600d8eb-f7cc-4592-b3d6-ef5c4220b89f" width="25%" title="todo-cb0">
<img src="https://github.com/user-attachments/assets/0c156109-4ae8-4239-8813-baf68b3b43eb" width="25%" title="todo-cb1">
<img src="https://github.com/user-attachments/assets/5a92a42f-9174-44a0-896a-65e0e391a428" width="25%" title="todo-cb2">
</div>

- SwiftDo (iOS): this app reckognizes 2/3 tasks as completed, but restores only one correctly with priority
<div>
<img src="https://github.com/user-attachments/assets/c8d28434-2e91-48dc-9790-1ea6a0ee6c73" width="25%" title="swiftdo0">
<img src="https://github.com/user-attachments/assets/8b5787ed-2777-42fd-b16f-fca514aa946e" width="25%" title="swiftdo1">
<img src="https://github.com/user-attachments/assets/da030f68-7178-4979-81e8-3423d780eaf6" width="25%" title="swiftdo2">
</div>

- 2do.txt (iOS): this app shows 3 tasks done, but only one restores correctly with priority and date, two restored show the creation date correctly
<div>
<img src="https://github.com/user-attachments/assets/7aec6caa-6861-4a07-ab66-dfe44079d6bb" width="25%" title="2do.txt0">
<img src="https://github.com/user-attachments/assets/f2d8779a-859a-4e1b-a167-3728edbdd2ff" width="25%" title="2do.txt3">
</div>

- todd (python, on MacOS/linux): this shows 3 tasks done, two correct with completion date, two restore properly (one with correct priority)
<img width="65%" title="todd0" src="https://github.com/user-attachments/assets/0af367ee-5fa3-4024-b1d5-ab4c501a01f4">
<img width="65%" title="todd1" src="https://github.com/user-attachments/assets/a79a04a3-1145-4512-ba15-e26cc662f3d0">
<img width="65%" title="todd2" src="https://github.com/user-attachments/assets/6f385ec2-1228-47bf-9467-71fb1643ecec">

- todo-txt-tui (python, on MacOS/linux): this app seems to be pretty agnostic of the arrangement of priority/completion/creation dates, however, completion of the undone tasks yields consistently the same format as your plugin (if I recall correctly)
<img width="65%" alt="todo-txt-tui0" src="https://github.com/user-attachments/assets/a042bfeb-a16e-4079-9995-5e9206b1e462">
<img width="65%" alt="todo-txt-tui1" src="https://github.com/user-attachments/assets/ece1f262-c920-4588-82b5-905858f6b665">
<img width="65%" alt="todo-txt-tui2" src="https://github.com/user-attachments/assets/52c7f899-7ac6-4728-867f-66f49bf9a304">
<img width="65%" alt="todo-txt-tui3" src="https://github.com/user-attachments/assets/c7e11ea4-da75-4a4f-8414-d986cc435680">
<img width="65%" alt="todo-txt-tui3done" src="https://github.com/user-attachments/assets/36365fc4-e9e0-4156-8abc-b76c8f99fd4c">
<img width="65%" alt="todo-txt-tui3done_src" src="https://github.com/user-attachments/assets/4010ba0d-55d6-4896-8ede-4bb1c1990162">

**Comment by benjamonnguyen** [comment]
Wow! Thanks for the detailed tests. Referencing the official specs (https://github.com/todotxt/todo.txt?tab=readme-ov-file#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space), it looks like priority is typically discarded. What are your thoughts on this?

**Comment by udjer** [comment]
Yeah, the official specs seem to recommend (though not demand) to use the format `pri:X` to preserve priority in completed tasks - to me, it seems not necessary to preserve priority:
- first reason: after completion, a task no longer has any priority;
- second reason: in the rare cases, where a task may get reactivated, a new priority is usually assigned anyways.

The original bash script seems to discard priority on task completion (at least, that seems to be the default).  But, of course, other people may use priorities differently, hence feel differently about preserving those.

SwiftDo and 2do.txt, for example, offer three options: discard priority, preserve it in the format `(X)`, preserve it in the format `pri:X`.  Thus, I deduce, that each of these options have their followers.

**Comment by benjamonnguyen** [comment]
https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/releases/tag/0.3.1
