### ISSUE TITLE
Sorting is not clear

### ISSUE THREAD

**Issue by ksdavidc** [benjamonnguyen/obsidian-inline-todotxt#30]
What i like about using blocks is to be able ot create different views of my todos, according to the sort.  To that end, I would like to be able to sort in a couple of different ways but can't figure out how:

For example, priority then by projects  (alphanum). 
I can focus on the top priority in each project
```
All the As
 proj a ctx 1
 proj b ctx 3
 proj c ctx 2
All the Bs
etc
```

priority then by contexts (alphanum). 
or the top priority in each context
```
All the As
 ctx 1 proj a
 ctx 2 proj c
 ctx 3 proj b
All the Bs
etc
```

or priority, then by date
i.e. what I have to do first today
```
A
today
tomorrow
B
today
tomorrow
```

The readme is a bit unclear to me.

**Comment by benjamonnguyen** [comment]
Hey! I agree that sorting could be much more user friendly and I have dropdown based sorting in the pipeline.

For now here's how to achieve the examples you provided:
![image](https://github.com/user-attachments/assets/3c0b5c7c-acc3-4f30-8f1a-17a3bcdc3b4d)

![image](https://github.com/user-attachments/assets/0508e20f-1e7c-4ddb-a09a-760a81384aa0)

![image](https://github.com/user-attachments/assets/47045c27-a4bd-4ae6-8fe5-f9f78868ed8c)
