### ISSUE TITLE
star does not work on files in folders that have spaces

### ISSUE THREAD

**Issue by ksdavidc** [benjamonnguyen/obsidian-inline-todotxt#34]
I believe, according to rough testing, that clicking star to add a priority does not work if the todo.txt file is in a folder which has spaces. (see https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/issues/27)

**Comment by benjamonnguyen** [comment]
The priority button seems to not work with file sync entirely. On the docket to hot fix!

**Comment by benjamonnguyen** [comment]
https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/releases/tag/0.7.0
