### ISSUE TITLE
two todo codeblock in one file does not work

### ISSUE THREAD

**Issue by ksdavidc** [benjamonnguyen/obsidian-inline-todotxt#35]
If I add 2 codeblocks to the same file referencing the same source, making changes to one does not update the other, even though it too should get updated.

The src file does get updated.

I sometimes want to have two blocks in the same file, as they can be sorted differently.

**Comment by ksdavidc** [comment]
A popup appears, but nothing in the console:

https://github.com/user-attachments/assets/d0044c6e-82db-411f-86c3-3c7454d156a8

**Comment by benjamonnguyen** [comment]
What change are you making in this example?

**Comment by ksdavidc** [comment]
Oops, wrong video, was supposed to go to a different issue. Actually, on retesting I can't seem to get consistent behavior, jsut a combination of not being able to apply stars, not being able to change entries, etc. I will close this until I can really figure out what is going on.

**Comment by benjamonnguyen** [comment]
Working on a feature to add support for multiple linked codeblocks

**Comment by benjamonnguyen** [comment]
https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/releases/tag/0.7.0

@ksdavidc there's still a rendering issue where the title of linked codeblocks higher than the one edited won't populate correctly, but functionality should be there
