### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by novakwh** [benjamonnguyen/obsidian-inline-todotxt#40]
Hi, I get a "failed to install" plugin when I try to install the plugin. I see a similar issue was closed in  #26 but it is not working for me now. Linux AppImage (1.6.7). 

From the console:

app.js:1 Error: Request failed, status 404
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

**Comment by benjamonnguyen** [comment]
Sorry about that. Resolved!

**Comment by novakwh** [comment]
That was fast, thanks! This is a really useful plugin.

**Comment by benjamonnguyen** [comment]
@novakwh thank you! I have a big release for mobile users coming soon!
